### PR TITLE
Fix #18: Changes made to load model at start

### LINKED ISSUE #18: Load models when the server starts.
When we were developing the pipeline, the models were loading as the pipeline proceeds since it won't have any effect on the total inference time. But when deploying the models, it is better to load them in the RAM when the server starts so that the response time could get reduced and it will also reduce the load on the server.
Keep in mind to load the models in such a way that it won't affect the pipeline when we try to run `python detection.py -i [image-path]` command.

### PR DESCRIPTION
**Pull request by Anubhav-Bhargava**
I have made changes to the API so that all the model weights are loaded at start-up of the server and it won't affect the pipeline when we try to run `python detection.py -i [image-path]` command.

### CODE REVIEW

**Comment by sgrpanchal31** [comment]
@Anubhav-Bhargava Two models are present in the pipeline. This PR only loads one. The second model is the text detection model that is called after the table detection step is done. That model is currently called via a function. Change that function to a class and load it in the `load_model()` function too.

**Comment by Anubhav-Bhargava** [comment]
I've made the required changes, please review :)

**Comment by Anubhav-Bhargava** [comment]
Any updates on the review of this particular PR?

**Comment by sgrpanchal31** [comment]
Hi Bhargav, I just got free from my previous commitments, and I will review and merge this PR before this weekend.

**Pull request merged**
